attributes:
  LastSwiftUpdateCheck: 1240
  LastUpgradeCheck: 1240
configs:
  Debug: debug
  Release: release
name: JACET8000
packages:
    Firebase:
        url: https://github.com/firebase/firebase-ios-sdk
        branch: 7.0-spm-beta
    SnapKit:
        url: https://github.com/SnapKit/SnapKit
        majorVersion: 5.0.1
    RxSwift:
        url: https://github.com/ReactiveX/RxSwift.git
        majorVersion: 6.1.0
    Rswift:
        url: https://github.com/mac-cain13/R.swift.Library
        majorVersion: 5.4.0
options:
  defaultConfig: Release
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
settings:
  configs:
    Debug:
      CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
      IPHONEOS_DEPLOYMENT_TARGET: 14.4
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      MTL_FAST_MATH: YES
      SDKROOT: iphoneos
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: -Onone
    Release:
      CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
      IPHONEOS_DEPLOYMENT_TARGET: 14.4
      MTL_FAST_MATH: YES
      SDKROOT: iphoneos
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
targets:
  JACET8000:
    dependencies:
        - package: Firebase
          product: FirebaseAuth
        - package: SnapKit
        - package: RxSwift
          product: RxCocoa
        - package: Rswift
    deploymentTarget: "14.4"
    platform: iOS
    prebuildScripts:
      - name: Run SwiftLint
        script: |
                if which swiftlint >/dev/null; then
                    swiftlint --fix
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
      - name: Run RSwift
        script: |
                if which rswift >/dev/null; then
                    rswift generate "$SRCROOT/$TARGET_NAME/Generated/R.generated.swift"
                else
                    echo "error: R.swift not installed; run 'mint bootstrap' to install"
                    return -1
                fi
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/$TARGET_NAME/Generated/R.generated.swift
    settings:
      configs:
        Debug:
          ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: WV6D96BG4D
          INFOPLIST_FILE: JACET8000/Sources/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: makoto.sato.JACET8000
          URL_SCHEMES: com.googleusercontent.apps.716193775936-juva1sqg1g92roesea5u1insdlv0oth9
          SWIFT_VERSION: 5.0
        Release:
          ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: WV6D96BG4D
          INFOPLIST_FILE: JACET8000/Sources/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: makoto.sato.JACET8000
          URL_SCHEMES: com.googleusercontent.apps.716193775936-juva1sqg1g92roesea5u1insdlv0oth9
          SWIFT_VERSION: 5.0
    sources:
    - name: JACET8000
      path: JACET8000
    type: application
